### ISSUE TITLE
TreeMenu 페이지 점검

### ISSUE THREAD

**Issue by DevelopKim** [SPAAAADE/sp.framework#15]
- gnb 에서 tree menu 영역 스타일 수정
  - 높이가 안맞는 경우 생김
- 예제 메뉴의 위, 아래 아이콘 위치 수정
  - 모바일의 트리메뉴와 같게 수정 요청
- 모든 스타일은 인라인으로 해주셈

**Comment by chocoma87** [comment]
b1767e2f118cb45e61e7ac46aa7dd0e0c0be954b
