### ISSUE TITLE
tab 플러그인 구조 바꾸기

### ISSUE THREAD

**Issue by chocoma87** [SPAAAADE/sp.framework#21]
- 마크업 수정 
  h3 -> ul 
  data-tab 삭제
  href, id 사용
- 플러그인 수정
- css 는 인라인으로 작성

**Comment by chocoma87** [comment]
- 마크업 수정 완료 bd433590029208966ad37f0a875f2b7f38403ed7
- 나머지는 @DevelopKim 해주셈

**Comment by DevelopKim** [comment]
- #4 이슈와 함께 처리 예정
