### ISSUE TITLE
탭 플러그인 개선사항

### ISSUE THREAD

**Issue by DevelopKim** [SPAAAADE/sp.framework#4]
- 옵션을 저장하는 멤버를 Public 멤버가 아닌 Private 으로 변경 
  -  `$.fn.sptab` 으로 시작 하는 멤버를 `var 변수명` 으로 수정
  - `spaccordion` 코드 참조
- event 등록하는 코드를 delegate events 방식으로 수정
  - [jQuery API 문서](http://api.jquery.com/on/#on-events-selector-data-handler) 참고
  - event 등록 함수도 Private 으로 수정한다.  
  - ui.js 106,107라인 참조

**Comment by chocoma87** [comment]
- 7e98c25a1295c76ecc497d1f017482c0bb098ebb
