### ISSUE TITLE
gnb 메뉴 이벤트에 대한 통합

### ISSUE THREAD

**Issue by DevelopKim** [SPAAAADE/sp.framework#6]
- $(document).ready 안의 항목들을 하나로 통합
- ui.js 의 상단에 이벤트와 gnb 관련 코드를 하나의 document.ready 영역으로 이동

**Comment by chocoma87** [comment]
알겠습니다.

**Comment by chocoma87** [comment]
답장으로 댓글이 써지나?

2015년 6월 25일 목요일, Develop.Kimnotifications@github.com님이 작성한 메시지:

> - $(document).ready 안의 항목들을 하나로 통합
> - ui.js 의 상단에 이벤트와 gnb 관련 코드를 하나의 document.ready 영역으로 이동
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SPAAAADE/sp.framework/issues/6.

## 

_Moon, Shin Woo_

webpublisher

010 6319 6489

moon@spaaaade.com lee@spaaaade.com

_SPAAAADE co.,ltd_.

## 

*A *3F 88-8, Cheongdam-dong, Gangnam-gu, Seoul, Korea

_T_ 02 333 9030  _F_ 02 333 9029

_E_ contact@spaaaade.com

spaaaade.com

**Comment by DevelopKim** [comment]
- ui.js 에는 플러그인 코드만 남기고 document.ready 영역은 custom.js 로 이동 하시오~ 
- #8 참고
