### ISSUE TITLE
플러그인 실행 코드 이전

### ISSUE THREAD

**Issue by DevelopKim** [SPAAAADE/sp.framework#8]
- 현재 ui.js 에는 플러그인 코드만 남겨둔다.
- 실제 페이지에서 플러그인을 실행하는 코드는 각 페이지에 인라인 스크립트에서 지정한다.

**Comment by chocoma87** [comment]
@DevelopKim 당장 진행 하시오!!!

**Comment by chocoma87** [comment]
- f188dfa1386dc7ee2eeb89022fe042df85fbeebc
- 완ㅋ료ㅋ
